# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/release/val_ntu_sk_120.npy
  label_path: ./data/release/val_label_120.pkl
  debug: False

label_count_path: ./data/release/train_label_120_count.pkl

# model
model: model.agcn.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 1
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0]
test_batch_size: 128
weights: ./ckpts/wfl_ntu_sk_120_agcn_joint_const_lr_1e-3-157-60356.pt

work_dir: ./work_dir/babel_v1.0/test_runs/test_wfl_ntu_sk_120_agcn_joint_const_lr_1e-3
save_score: True
